export type ButtonQuote = {
    attribution: string | null;
    quote: string;
}

export const locked_quotes: ButtonQuote[] = [
    { attribution: "Phar",          quote: "NO WIN :(" },
    { attribution: "Phar",          quote: "I'M UNPRESSABLE!" },
    { attribution: "Phar",          quote: "NO" },
    { attribution: "Phar",          quote: "NO KEYS?" },
    { attribution: "Phar",          quote: "DEPRESSION" },
    { attribution: "Phar",          quote: "NO SATISFACTION" },
    { attribution: "Phar",          quote: "PHAR SAID NO" },
    { attribution: "Phar",          quote: "PUSH ME /S" },
    { attribution: "Phar",          quote: "PHAR WHY" },
    { attribution: "Phar",          quote: "ASK AGAIN LATER" },
    { attribution: "Phar",          quote: "I'M NOT IN THE MOOD" },
    { attribution: "Phar",          quote: "LOADING..." },
    { attribution: "Phar",          quote: "NON" },
    { attribution: "Phar",          quote: "NEIN" },
    { attribution: "Phar",          quote: "नहीं" },
    { attribution: "Phar",          quote: "いいえ" },
    { attribution: "Phar",          quote: "아니요" },
    { attribution: "Qwazzy",        quote: "THERE IS NO BUTTON" },
    { attribution: "Qwazzy",        quote: "NOPE.AVI" },
    { attribution: "Qwazzy",        quote: "OUT OF ORDER" },
    { attribution: "Bokyubi",       quote: "I'M IN BK... AGAIN!" },
    { attribution: "Kappatechy",    quote: "DEPOSIT 500 RUPEES TO UNLOCK" },
    { attribution: "Hopop",         quote: "DO NOT CLIQUE" },
    { attribution: "Gesellschaft",  quote: "THAT WAS HARD" },
    { attribution: "Gesellschaft",  quote: "SKILL ISSUE" },
    { attribution: "Anonymous",     quote: ">:3" },
    { attribution: "Anonymous",     quote: "JUST USE A KEYBLADE TO UNLOCK THIS" },
    { attribution: "Anonymous",     quote: ">_<" },
    { attribution: "Anonymous",     quote: "ADREM WHY" },
    { attribution: "Anonymous",     quote: "NO BOOPS ALLOWED" },
    { attribution: "Anonymous",     quote: "I HOPE YOU'RE HAVING A NICE DAY" },
    { attribution: "StevenRoy",     quote: "I'M AFRAID I CAN'T DO THAT DAVE" },
    { attribution: "StevenRoy",     quote: "SOON™" },
    { attribution: "StevenRoy",     quote: "WAIT FOR IT, WAIT FOR IT..." },
    { attribution: "StevenRoy",     quote: "THINGS COME TO THOSE WHO WAIT..." },
    { attribution: "StevenRoy",     quote: "INSTALLING UPDATE (1%), PLEASE WAIT" },
    { attribution: "StevenRoy",     quote: "STAND BY, FOR ACTION!" },
    { attribution: "MadiMadsen",    quote: "CLIQUE 2: ELECTRIC BOOGALOO" },
    { attribution: "Mav",           quote: "WHEN TO PRESS?" },
    { attribution: "Mav",           quote: "JUST FIVE MORE MINUTES..." },
    { attribution: "Mav",           quote: "NEVER GONNA LET YOU CLICK" },
    { attribution: "Mav",           quote: "NEVER GONNA PRESS YOU DOWN" },
    { attribution: "Mav",           quote: "NEVER GONNA CLIQUE AROUND" },
    { attribution: "Mav",           quote: "... AND HURT YOU" },
    { attribution: "Phar",          quote: "I HAVE TO ASK MY MOM FIRST" },
    { attribution: "Scipio Wright", quote: ".: :;" },
];

export const button_quotes: ButtonQuote[] = [
    { attribution: "Phar",          quote: "PUSH ME" },
    { attribution: "Phar",          quote: "CLIQUE HERE" },
    { attribution: "Phar",          quote: "DO NOT PUSH" },
    { attribution: "Phar",          quote: "I LOVE YOU" },
    { attribution: "Phar",          quote: "WIN PLZ" },
    { attribution: "Phar",          quote: "HI! :)" },
    { attribution: "Phar",          quote: "DESTROY ALL HUMANS" },
    { attribution: "Phar",          quote: "RELEASE CLIQUE 2" },
    { attribution: "Phar",          quote: "YES!" },
    { attribution: "Phar",          quote: "END THE WORLD" },
    { attribution: "Phar",          quote: "EXPLODE" },
    { attribution: "Quazzy",        quote: "I'M NOT A NUCLEAR LAUNCH BUTTON, I PROMISE" },
    { attribution: "Quazzy",        quote: "DID YOU CHECK AGINAH FIRST?" },
    { attribution: "Quazzy",        quote: "PROGRESSION BALANCING: MAYBE" },
    { attribution: "Quazzy",        quote: "OBLIGATION FULFILLED™" },
    { attribution: "Quazzy",        quote: "YOU DID THE THING!" },
    { attribution: "Kappatechy",    quote: "!RELEASE" },
    { attribution: "Hopop",         quote: "READY FOR RELEASE" },
    { attribution: "Hopop",         quote: "BLAME PHAR" },
    { attribution: "Hopop",         quote: "SHENANIGANS INCOMING" },
    { attribution: "Hopop",         quote: "ONE OF THE GAMES OF ALL TIME" },
    { attribution: "Hopop",         quote: "LOOKING FOR SOMETHING ELSE?" },
    { attribution: "Gesellschaft",  quote: "THAT WAS EASY" },
    { attribution: "Gesellschaft",  quote: "SQUEAKY" },
    { attribution: "Gesellschaft",  quote: "AWOOGA!" },
    { attribution: "Gesellschaft",  quote: "FIRE ZE MISSILES" },
    { attribution: "Anonymous",     quote: "I BET IT'S A MOON PEARL" },
    { attribution: "Anonymous",     quote: "LET'S PLAY BUTTON PUSHING GAME" },
    { attribution: "Anonymous",     quote: ":3" },
    { attribution: "Anonymous",     quote: "OWO WHAT'S THIS? *NOTICES YOUR MOUSE CURSOR*" },
    { attribution: "Anonymous",     quote: "BUTTONMAN: PHAR FROM HOME" },
    { attribution: "Anonymous",     quote: "PRESS PRESS FALL IN LOVE" },
    { attribution: "Anonymous",     quote: "PRESS TO SUBMIT DEATHLINK" },
    { attribution: "Anonymous",     quote: "CLIQUE? CRINGE AF" },
    { attribution: "Anonymous",     quote: "SEND PHAR MORE RANSOMWARE" },
    { attribution: "Bokyubi",       quote: "WHO TURNED ON PROGRESSION BALANCING?" },
    { attribution: "StevenRoy",     quote: "OPEN THE POD BAY DOORS" },
    { attribution: "StevenRoy",     quote: "KICK SOME SERIOUS BUTTON" },
    { attribution: "StevenRoy",     quote: "START GAME" },
    { attribution: "StevenRoy",     quote: "PUSH TO ACHIEVE ENLIGHTENMENT" },
    { attribution: "StevenRoy",     quote: "POPCORN" },
    { attribution: "StevenRoy",     quote: "BOOP THE SNOOT" },
    { attribution: "Mav",           quote: "DISENCHANT YOUR HEARTHSTONE CARDS" },
    { attribution: "Mav",           quote: "NOW!" },
    { attribution: "Mav",           quote: "TAKE ME, I'M READY" },
];

export function getRandomQuote(locked = false) {
    const array = locked ? locked_quotes : button_quotes;
    return array[Math.floor(Math.random() * array.length)];
}
